version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup-fxgrip
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']
