/*!
	@file       FxGripFMMExpansion.m
	@copyright  Copyright © 2024 Belisoful All rights reserved.
	@author     belisoful
	@date       2026-09-08
	@header     FxGripFMMExpansion
	@abstract   Implements the Cartesian multipole machinery.
	@discussion Introduced in FxGrip 0.1.0. The derivatives of 1/r are generated by symbolic
	            differentiation: 1/r is stored as one term, coefficient one, monomial 1, r-power 1, and
	            each further derivative applies the product and chain rule to every term, so the tables
	            are correct by construction rather than by a recalled recurrence. A derivative is then a
	            polynomial in the coordinates over odd powers of r, evaluated by table lookup of the
	            precomputed powers.
*/

#include "FxGripFMMExpansion.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

// One term of a derivative of 1/r: coef * x^a y^b z^c * r^(-m).
typedef struct {
	double coef;
	uint8_t a, b, c, m;
} FxGripFMMDerivTerm;

typedef struct {
	FxGripFMMDerivTerm *terms;
	uint32_t count;
	uint32_t capacity;
} FxGripFMMTermList;

struct FxGripFMMExpansionTables {
	uint32_t P;          // moment order
	uint32_t K;          // derivative order = P + 1
	uint32_t momentCount;
	uint32_t derivCount;

	uint8_t *ma, *mb, *mc;   // moment multi-indices, length momentCount
	float   *invFactorial;   // 1/(a! b! c!) per moment
	float   *sign;           // (-1)^|α| per moment

	int32_t *derivIndex;     // (a,b,c) -> derivative index, size (K+1)^3, -1 if invalid
	int32_t *momentPlus[3];  // per moment α, derivative index of α+e_axis
	int32_t *momentIndex;    // (a,b,c) -> moment index, size (P+1)^3, -1 if invalid
	int32_t *sumIndex;       // [β*momentCount + α] -> derivative index of α+β

	FxGripFMMTermList *derivTerms; // length derivCount

	uint32_t maxExponent;    // max single-axis exponent across all derivative terms
	uint32_t maxRPower;      // max r-power m across all derivative terms
};

#pragma mark Multi-index tables

uint32_t FxGripFMMTermCount(uint32_t order)
{
	return (order + 1u) * (order + 2u) * (order + 3u) / 6u;
}

static void FxGripFMMEnumerate(uint32_t order, uint8_t *a, uint8_t *b, uint8_t *c)
{
	uint32_t idx = 0;
	for (uint32_t total = 0; total <= order; total++) {
		for (uint32_t ai = 0; ai <= total; ai++) {
			for (uint32_t bi = 0; bi <= total - ai; bi++) {
				const uint32_t ci = total - ai - bi;
				a[idx] = (uint8_t)ai; b[idx] = (uint8_t)bi; c[idx] = (uint8_t)ci;
				idx++;
			}
		}
	}
}

static double FxGripFMMFactorial(uint32_t n)
{
	double f = 1.0;
	for (uint32_t i = 2; i <= n; i++) {
		f *= (double)i;
	}
	return f;
}

#pragma mark Symbolic differentiation of 1/r

static void FxGripFMMTermListAdd(FxGripFMMTermList *list, double coef, uint8_t a, uint8_t b, uint8_t c, uint8_t m)
{
	if (coef == 0.0) {
		return;
	}
	for (uint32_t i = 0; i < list->count; i++) {
		FxGripFMMDerivTerm *t = &list->terms[i];
		if (t->a == a && t->b == b && t->c == c && t->m == m) {
			t->coef += coef;
			return;
		}
	}
	if (list->count == list->capacity) {
		list->capacity = list->capacity ? list->capacity * 2u : 8u;
		list->terms = (FxGripFMMDerivTerm *)realloc(list->terms, sizeof(FxGripFMMDerivTerm) * list->capacity);
	}
	list->terms[list->count].coef = coef;
	list->terms[list->count].a = a;
	list->terms[list->count].b = b;
	list->terms[list->count].c = c;
	list->terms[list->count].m = m;
	list->count++;
}

// Differentiates a term list with respect to one axis, appending into `out`.
// d/dx [coef x^a y^b z^c r^-m] = coef a x^(a-1) y^b z^c r^-m  -  coef m x^(a+1) y^b z^c r^-(m+2).
static void FxGripFMMDifferentiate(const FxGripFMMTermList *in, uint32_t axis, FxGripFMMTermList *out)
{
	for (uint32_t i = 0; i < in->count; i++) {
		const FxGripFMMDerivTerm t = in->terms[i];
		uint8_t e[3] = { t.a, t.b, t.c };
		if (e[axis] > 0) {
			uint8_t down[3] = { t.a, t.b, t.c };
			down[axis] = (uint8_t)(e[axis] - 1u);
			FxGripFMMTermListAdd(out, t.coef * (double)e[axis], down[0], down[1], down[2], t.m);
		}
		uint8_t up[3] = { t.a, t.b, t.c };
		up[axis] = (uint8_t)(e[axis] + 1u);
		FxGripFMMTermListAdd(out, -t.coef * (double)t.m, up[0], up[1], up[2], (uint8_t)(t.m + 2u));
	}
}

#pragma mark Table construction

static inline uint32_t FxGripFMMFlatten(uint32_t a, uint32_t b, uint32_t c, uint32_t stride)
{
	return (a * stride + b) * stride + c;
}

FxGripFMMExpansionTables *FxGripFMMExpansionTablesCreate(uint32_t order)
{
	FxGripFMMExpansionTables *tables = (FxGripFMMExpansionTables *)calloc(1, sizeof(FxGripFMMExpansionTables));
	if (tables == NULL) {
		return NULL;
	}
	tables->P = order;
	tables->K = (2u * order > order + 1u) ? 2u * order : order + 1u; // 2P covers M2L (α+β up to 2P)
	tables->momentCount = FxGripFMMTermCount(order);
	tables->derivCount = FxGripFMMTermCount(tables->K);

	tables->ma = (uint8_t *)malloc(tables->momentCount);
	tables->mb = (uint8_t *)malloc(tables->momentCount);
	tables->mc = (uint8_t *)malloc(tables->momentCount);
	tables->invFactorial = (float *)malloc(sizeof(float) * tables->momentCount);
	tables->sign = (float *)malloc(sizeof(float) * tables->momentCount);
	FxGripFMMEnumerate(order, tables->ma, tables->mb, tables->mc);
	for (uint32_t k = 0; k < tables->momentCount; k++) {
		const uint32_t a = tables->ma[k], b = tables->mb[k], c = tables->mc[k];
		tables->invFactorial[k] = (float)(1.0 / (FxGripFMMFactorial(a) * FxGripFMMFactorial(b) * FxGripFMMFactorial(c)));
		tables->sign[k] = ((a + b + c) & 1u) ? -1.0f : 1.0f;
	}

	// Derivative multi-indices and their inverse map.
	uint8_t *da = (uint8_t *)malloc(tables->derivCount);
	uint8_t *db = (uint8_t *)malloc(tables->derivCount);
	uint8_t *dc = (uint8_t *)malloc(tables->derivCount);
	FxGripFMMEnumerate(tables->K, da, db, dc);
	const uint32_t stride = tables->K + 1u;
	tables->derivIndex = (int32_t *)malloc(sizeof(int32_t) * stride * stride * stride);
	for (uint32_t i = 0; i < stride * stride * stride; i++) {
		tables->derivIndex[i] = -1;
	}
	for (uint32_t d = 0; d < tables->derivCount; d++) {
		tables->derivIndex[FxGripFMMFlatten(da[d], db[d], dc[d], stride)] = (int32_t)d;
	}

	// Symbolic derivative term lists, generated from 1/r by one differentiation per order step.
	tables->derivTerms = (FxGripFMMTermList *)calloc(tables->derivCount, sizeof(FxGripFMMTermList));
	tables->maxExponent = 0;
	tables->maxRPower = 1;
	for (uint32_t d = 0; d < tables->derivCount; d++) {
		const uint32_t a = da[d], b = db[d], c = dc[d];
		if (a + b + c == 0) {
			FxGripFMMTermListAdd(&tables->derivTerms[d], 1.0, 0, 0, 0, 1);
		} else {
			// Differentiate the parent that has one lower exponent on the first nonzero axis.
			uint32_t axis = (a > 0) ? 0u : ((b > 0) ? 1u : 2u);
			uint32_t pa = a, pb = b, pc = c;
			if (axis == 0) { pa--; } else if (axis == 1) { pb--; } else { pc--; }
			const int32_t parent = tables->derivIndex[FxGripFMMFlatten(pa, pb, pc, stride)];
			FxGripFMMDifferentiate(&tables->derivTerms[parent], axis, &tables->derivTerms[d]);
		}
		for (uint32_t i = 0; i < tables->derivTerms[d].count; i++) {
			const FxGripFMMDerivTerm t = tables->derivTerms[d].terms[i];
			uint32_t me = t.a > t.b ? (t.a > t.c ? t.a : t.c) : (t.b > t.c ? t.b : t.c);
			if (me > tables->maxExponent) { tables->maxExponent = me; }
			if (t.m > tables->maxRPower) { tables->maxRPower = t.m; }
		}
	}

	// For each moment α, the derivative index of α + e_axis, used by the field evaluation.
	for (uint32_t axis = 0; axis < 3; axis++) {
		tables->momentPlus[axis] = (int32_t *)malloc(sizeof(int32_t) * tables->momentCount);
	}
	for (uint32_t k = 0; k < tables->momentCount; k++) {
		uint32_t a = tables->ma[k], b = tables->mb[k], c = tables->mc[k];
		tables->momentPlus[0][k] = tables->derivIndex[FxGripFMMFlatten(a + 1u, b, c, stride)];
		tables->momentPlus[1][k] = tables->derivIndex[FxGripFMMFlatten(a, b + 1u, c, stride)];
		tables->momentPlus[2][k] = tables->derivIndex[FxGripFMMFlatten(a, b, c + 1u, stride)];
	}

	// Moment multi-index inverse map, for the translation operators' shift lookups.
	const uint32_t mstride = order + 1u;
	tables->momentIndex = (int32_t *)malloc(sizeof(int32_t) * mstride * mstride * mstride);
	for (uint32_t i = 0; i < mstride * mstride * mstride; i++) {
		tables->momentIndex[i] = -1;
	}
	for (uint32_t k = 0; k < tables->momentCount; k++) {
		tables->momentIndex[FxGripFMMFlatten(tables->ma[k], tables->mb[k], tables->mc[k], mstride)] = (int32_t)k;
	}

	// For M2L: the derivative index of α+β for every moment pair (β outer, α inner).
	tables->sumIndex = (int32_t *)malloc(sizeof(int32_t) * tables->momentCount * tables->momentCount);
	for (uint32_t b = 0; b < tables->momentCount; b++) {
		for (uint32_t a = 0; a < tables->momentCount; a++) {
			const uint32_t sa = tables->ma[a] + tables->ma[b];
			const uint32_t sb = tables->mb[a] + tables->mb[b];
			const uint32_t sc = tables->mc[a] + tables->mc[b];
			tables->sumIndex[b * tables->momentCount + a] = tables->derivIndex[FxGripFMMFlatten(sa, sb, sc, stride)];
		}
	}

	free(da); free(db); free(dc);
	return tables;
}

void FxGripFMMExpansionTablesDestroy(FxGripFMMExpansionTables *tables)
{
	if (tables == NULL) {
		return;
	}
	free(tables->ma); free(tables->mb); free(tables->mc);
	free(tables->invFactorial); free(tables->sign);
	free(tables->derivIndex);
	free(tables->momentIndex);
	free(tables->sumIndex);
	for (uint32_t axis = 0; axis < 3; axis++) {
		free(tables->momentPlus[axis]);
	}
	if (tables->derivTerms != NULL) {
		for (uint32_t d = 0; d < tables->derivCount; d++) {
			free(tables->derivTerms[d].terms);
		}
		free(tables->derivTerms);
	}
	free(tables);
}

uint32_t FxGripFMMExpansionOrder(const FxGripFMMExpansionTables *tables) { return tables->P; }
uint32_t FxGripFMMExpansionMomentCount(const FxGripFMMExpansionTables *tables) { return tables->momentCount; }

uint32_t FxGripFMMExpansionDerivativeCount(const FxGripFMMExpansionTables *tables)
{
	return tables != NULL ? tables->derivCount : 0u;
}

int32_t FxGripFMMDerivativeIndex(const FxGripFMMExpansionTables *tables, uint32_t a, uint32_t b, uint32_t c)
{
	if (a + b + c > tables->K) {
		return -1;
	}
	const uint32_t stride = tables->K + 1u;
	return tables->derivIndex[FxGripFMMFlatten(a, b, c, stride)];
}

#pragma mark Evaluation

void FxGripFMMEvalDerivatives(const FxGripFMMExpansionTables *tables,
							  float ux, float uy, float uz, float *out)
{
	const double r2 = (double)ux * ux + (double)uy * uy + (double)uz * uz;
	const double rinv = 1.0 / sqrt(r2);

	// Powers of the coordinates and of 1/r, indexed directly by exponent.
	double xp[16], yp[16], zp[16], rp[64];
	const uint32_t maxE = tables->maxExponent;
	const uint32_t maxM = tables->maxRPower;
	xp[0] = yp[0] = zp[0] = 1.0;
	for (uint32_t e = 1; e <= maxE; e++) {
		xp[e] = xp[e - 1] * (double)ux;
		yp[e] = yp[e - 1] * (double)uy;
		zp[e] = zp[e - 1] * (double)uz;
	}
	rp[0] = 1.0;
	for (uint32_t m = 1; m <= maxM; m++) {
		rp[m] = rp[m - 1] * rinv;
	}

	for (uint32_t d = 0; d < tables->derivCount; d++) {
		const FxGripFMMTermList *list = &tables->derivTerms[d];
		double value = 0.0;
		for (uint32_t i = 0; i < list->count; i++) {
			const FxGripFMMDerivTerm t = list->terms[i];
			value += t.coef * xp[t.a] * yp[t.b] * zp[t.c] * rp[t.m];
		}
		out[d] = (float)value;
	}
}

void FxGripFMMP2M(const FxGripFMMExpansionTables *tables,
				  float cx, float cy, float cz,
				  const float *sx, const float *sy, const float *sz, const float *ss, uint32_t ns,
				  float *moments)
{
	const uint32_t P = tables->P;
	for (uint32_t j = 0; j < ns; j++) {
		const double dx = (double)sx[j] - cx;
		const double dy = (double)sy[j] - cy;
		const double dz = (double)sz[j] - cz;
		double xp[8], yp[8], zp[8];
		xp[0] = yp[0] = zp[0] = 1.0;
		for (uint32_t e = 1; e <= P; e++) {
			xp[e] = xp[e - 1] * dx;
			yp[e] = yp[e - 1] * dy;
			zp[e] = zp[e - 1] * dz;
		}
		const double s = (double)ss[j];
		for (uint32_t k = 0; k < tables->momentCount; k++) {
			const double mono = xp[tables->ma[k]] * yp[tables->mb[k]] * zp[tables->mc[k]];
			moments[k] += (float)(s * mono * (double)tables->invFactorial[k]);
		}
	}
}

void FxGripFMMM2PField(const FxGripFMMExpansionTables *tables,
					   float cx, float cy, float cz, const float *moments,
					   const float *tx, const float *ty, const float *tz,
					   float *ex, float *ey, float *ez, uint32_t nt)
{
	float *deriv = (float *)malloc(sizeof(float) * tables->derivCount);
	for (uint32_t i = 0; i < nt; i++) {
		FxGripFMMEvalDerivatives(tables, tx[i] - cx, ty[i] - cy, tz[i] - cz, deriv);
		double fx = 0.0, fy = 0.0, fz = 0.0;
		for (uint32_t k = 0; k < tables->momentCount; k++) {
			const double sm = (double)tables->sign[k] * (double)moments[k];
			fx += sm * (double)deriv[tables->momentPlus[0][k]];
			fy += sm * (double)deriv[tables->momentPlus[1][k]];
			fz += sm * (double)deriv[tables->momentPlus[2][k]];
		}
		ex[i] += (float)fx;
		ey[i] += (float)fy;
		ez[i] += (float)fz;
	}
	free(deriv);
}

#pragma mark Translation operators

static double FxGripFMMBinomial(uint32_t n, uint32_t k)
{
	if (k > n) {
		return 0.0;
	}
	return FxGripFMMFactorial(n) / (FxGripFMMFactorial(k) * FxGripFMMFactorial(n - k));
}

void FxGripFMMM2M(const FxGripFMMExpansionTables *tables,
				  float ccx, float ccy, float ccz, const float *childMoments,
				  float cpx, float cpy, float cpz, float *parentMoments)
{
	const uint32_t P = tables->P;
	const double dx = (double)ccx - cpx, dy = (double)ccy - cpy, dz = (double)ccz - cpz;
	double xp[8], yp[8], zp[8];
	xp[0] = yp[0] = zp[0] = 1.0;
	for (uint32_t e = 1; e <= P; e++) {
		xp[e] = xp[e - 1] * dx; yp[e] = yp[e - 1] * dy; zp[e] = zp[e - 1] * dz;
	}
	const uint32_t mstride = P + 1u;
	for (uint32_t pa = 0; pa < tables->momentCount; pa++) {
		const uint32_t aa = tables->ma[pa], ab = tables->mb[pa], ac = tables->mc[pa];
		double sum = 0.0;
		for (uint32_t pg = 0; pg < tables->momentCount; pg++) {
			const uint32_t ga = tables->ma[pg], gb = tables->mb[pg], gc = tables->mc[pg];
			if (ga > aa || gb > ab || gc > ac) {
				continue;
			}
			const uint32_t da = aa - ga, db = ab - gb, dc = ac - gc;
			const int32_t di = tables->momentIndex[FxGripFMMFlatten(da, db, dc, mstride)];
			sum += (double)childMoments[pg] * xp[da] * yp[db] * zp[dc] * (double)tables->invFactorial[di];
		}
		parentMoments[pa] += (float)sum;
	}
}

void FxGripFMMM2L(const FxGripFMMExpansionTables *tables,
				  float cmx, float cmy, float cmz, const float *moments,
				  float clx, float cly, float clz, float *local)
{
	float *deriv = (float *)malloc(sizeof(float) * tables->derivCount);
	FxGripFMMEvalDerivatives(tables, clx - cmx, cly - cmy, clz - cmz, deriv);
	const uint32_t mc = tables->momentCount;
	for (uint32_t pb = 0; pb < mc; pb++) {
		double sum = 0.0;
		const int32_t *row = &tables->sumIndex[pb * mc];
		for (uint32_t pa = 0; pa < mc; pa++) {
			sum += (double)tables->sign[pa] * (double)moments[pa] * (double)deriv[row[pa]];
		}
		local[pb] += (float)((double)tables->invFactorial[pb] * sum);
	}
	free(deriv);
}

void FxGripFMML2L(const FxGripFMMExpansionTables *tables,
				  float cpx, float cpy, float cpz, const float *parentLocal,
				  float ccx, float ccy, float ccz, float *childLocal)
{
	const uint32_t P = tables->P;
	const double dx = (double)ccx - cpx, dy = (double)ccy - cpy, dz = (double)ccz - cpz;
	double xp[8], yp[8], zp[8];
	xp[0] = yp[0] = zp[0] = 1.0;
	for (uint32_t e = 1; e <= P; e++) {
		xp[e] = xp[e - 1] * dx; yp[e] = yp[e - 1] * dy; zp[e] = zp[e - 1] * dz;
	}
	for (uint32_t pd = 0; pd < tables->momentCount; pd++) {
		const uint32_t da = tables->ma[pd], db = tables->mb[pd], dc = tables->mc[pd];
		double sum = 0.0;
		for (uint32_t pb = 0; pb < tables->momentCount; pb++) {
			const uint32_t ba = tables->ma[pb], bb = tables->mb[pb], bc = tables->mc[pb];
			if (ba < da || bb < db || bc < dc) {
				continue;
			}
			const uint32_t ea = ba - da, eb = bb - db, ec = bc - dc;
			const double coef = FxGripFMMBinomial(ba, da) * FxGripFMMBinomial(bb, db) * FxGripFMMBinomial(bc, dc);
			sum += (double)parentLocal[pb] * coef * xp[ea] * yp[eb] * zp[ec];
		}
		childLocal[pd] += (float)sum;
	}
}

void FxGripFMML2PField(const FxGripFMMExpansionTables *tables,
					   float clx, float cly, float clz, const float *local,
					   const float *tx, const float *ty, const float *tz,
					   float *ex, float *ey, float *ez, uint32_t nt)
{
	const uint32_t P = tables->P;
	for (uint32_t i = 0; i < nt; i++) {
		const double dx = (double)tx[i] - clx, dy = (double)ty[i] - cly, dz = (double)tz[i] - clz;
		double xp[8], yp[8], zp[8];
		xp[0] = yp[0] = zp[0] = 1.0;
		for (uint32_t e = 1; e <= P; e++) {
			xp[e] = xp[e - 1] * dx; yp[e] = yp[e - 1] * dy; zp[e] = zp[e - 1] * dz;
		}
		double fx = 0.0, fy = 0.0, fz = 0.0;
		for (uint32_t pb = 0; pb < tables->momentCount; pb++) {
			const uint32_t ba = tables->ma[pb], bb = tables->mb[pb], bc = tables->mc[pb];
			const double L = (double)local[pb];
			// E_i = Σ_β L_β β_i (t − c_L)^{β − e_i}.
			if (ba > 0) { fx += L * (double)ba * xp[ba - 1] * yp[bb] * zp[bc]; }
			if (bb > 0) { fy += L * (double)bb * xp[ba] * yp[bb - 1] * zp[bc]; }
			if (bc > 0) { fz += L * (double)bc * xp[ba] * yp[bb] * zp[bc - 1]; }
		}
		ex[i] += (float)fx;
		ey[i] += (float)fy;
		ez[i] += (float)fz;
	}
}
